"""Consolidated portfolio report rendering."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from .engine import AnalysisResult


_VERDICT_ICON = {"BUY": "🟢", "HOLD": "🟡", "AVOID": "🔴", "REVIEW": "⚪"}


def _cell(value: object) -> str:
    return str(value or "—").replace("|", "\\|").replace("\n", " ")


def render_report(
    results: Iterable[AnalysisResult],
    analysis_date: str,
    report_path: str | Path | None = None,
) -> str:
    items = list(results)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Indian Portfolio Analysis — TradingAgents",
        "",
        f"**Analysis date:** {analysis_date}  ",
        f"**Generated:** {generated}  ",
        f"**Stocks analyzed:** {len(items)}",
        "",
        "> Ratings are generated by the TradingAgents analyst, research, trader, risk, and portfolio-manager graph.",
        "> Mapping: Buy/Overweight → BUY; Hold → HOLD; Underweight/Sell → AVOID.",
        "",
        "## Summary",
        "",
        "| Stock | TradingAgents rating | Verdict | Sentiment confidence | Status |",
        "|---|---|---|---|---|",
    ]
    for item in items:
        icon = _VERDICT_ICON.get(item.verdict, "⚪")
        status = "Error" if item.error else "Complete"
        lines.append(
            f"| {_cell(item.ticker)} | {_cell(item.signal)} | {icon} {_cell(item.verdict)} "
            f"| {_cell(item.sentiment_confidence)} | {status} |"
        )

    lines.extend(["", "## Detailed decisions", ""])
    base = Path(report_path).parent if report_path else None
    for index, item in enumerate(items, 1):
        display_name = f" — {item.company_name}" if item.company_name else ""
        lines.extend(
            [
                f"### {index}. {item.ticker}{display_name}",
                "",
                f"**TradingAgents rating:** {item.signal}  ",
                f"**Portfolio verdict:** {_VERDICT_ICON.get(item.verdict, '⚪')} {item.verdict}  ",
                f"**Sentiment data confidence:** {item.sentiment_confidence}",
                "",
            ]
        )
        if item.error:
            lines.extend([f"**Analysis failed:** `{item.error}`", ""])
            continue
        if item.report_path:
            link = Path(item.report_path)
            if base:
                try:
                    link = link.relative_to(base)
                except ValueError:
                    pass
            lines.extend([f"[Open the complete multi-agent report]({link.as_posix()})", ""])
        lines.extend([item.final_decision.strip() or "No final decision returned.", "", "---", ""])

    lines.extend(
        [
            "## Disclaimer",
            "",
            "This AI-generated research is for informational and educational purposes only. "
            "It is not financial advice. Verify the source data and consult a SEBI-registered "
            "investment adviser before acting.",
            "",
        ]
    )
    return "\n".join(lines)
